# Generated by Django 4.2.6 on 2023-10-31 16:13

from django.db import migrations, models
import files_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('files_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=files_api.models.user_directory_path),
        ),
    ]
